### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by BITRABBBIT** [Theuntextured/electric-network-kit#1]
Hello, good asset. 

I wanted to suggest adding an optional option for power transmission in the network not by tick but by dispatchers. For example, you have a generator and a scale of 100%, we connect 1 lamp that requires 10% dispatcher is triggered, turns on the lamp and recalculates the energy in the network 90% for the generator. Thus, we will avoid useless ticks or timers, let's say 100 actors who have your logic, which in fact does nothing for more time. It would be really great if you thought about it, thank you!

**Comment by Theuntextured** [comment]
> 

I was thinking yesterday about changing the way power is distributed, I was thinking about having a system with a "power available" variable which changes accordingly. I will definitely do it as soon as I have time.
I sometimes look back at my old systems and think about how bad they are, and this is one of these cases. (while the asset is quite new on the market, I made it a while back but was unable to publish it due to age restrictions)
Thanks for the feedback and I apologize that the product was not up to standards in performance!

What I was thinking at the time was the kind of system that a tech Minecraft mod has, where energy is distributed every tick. I quite liked the idea and I wanted to make something like that. But for optimization purposes, I agree, it is quite dumb.

I will let you know when the new version is out!

**Comment by BITRABBBIT** [comment]
It's a pity I didn't see this system in the work you're talking about. I am not a big expert on energy, but as a developer I can assume that it is not so important that energy smoothly changes its state, in life we can only see an instant result of working with electricity, and therefore it would be good for productivity. In addition, I would venture to assume that the players will not notice all these smooth transitions anyway, but will see for the most part only turning on or off the light bulb.

**Comment by Theuntextured** [comment]
> 

Yep, I am aware now. Don't know why I was thinking what I was thinking back in November when I worked on this, but oh well. As I said, I will release an update soon.

**Comment by BITRABBBIT** [comment]
Thank you for your answers, looking forward to the update!

**Comment by Theuntextured** [comment]
> Thank you for your answers, looking forward to the update!

Thank you for buying my asset, you absolute legend!

**Comment by Theuntextured** [comment]
As promised, the new file update is out. It is currently being processed by Epic Games, but it should be out in a few hours.
Thanks again for the feedback! <3
